stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job-fe:       # This job runs in the build stage, which runs first.
  stage: build
  image: trion/ng-cli:10.2.0
  tags:
    - hva
  script:
    - npm install
    - ng build

build-job-be:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8-adoptopenjdk-15
  tags:
    - hva
  script:
    - cd spring-boot-backend
    - mvn compile

unit-test-job-be:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: maven:3.8-adoptopenjdk-15
  tags:
    - hva
  script:
    - cd spring-boot-backend
    - mvn test
    - echo "Eerst unit tests schrijven en dan hier de command toevoegen welke test files er gerund moet worden"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - hva
  script:
    - echo "Eerst uitzoeken hoe we willen deployen en dan hier de script toevoegen"
