stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - hvarunner1
  script:
    - ng build

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  tags:
    - hvarunner1
  script:
    - echo "Eerst unit tests schrijven en dan hier de command toevoegen welke test files er gerund moet worden"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - hvarunner1
  script:
    - echo "Eerst uitzoeken hoe we willen deployen en dan hier de script toevoegen"
